title = 'MatSch Web'
theme = 'PaperMod'
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true

[languages]

[languages.de]
baseURL = 'https://blog.matschcode.de/de'
languageName = "Deutsch"
weight = 1
contentDir = "content"

[languages.en]
baseURL = 'https://blog.matschcode.de/en'
languageName = "English"
weight = 2
contentDir = "content"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true

  mainSections = []

[params.assets]
  css = [
    "css/extended/custom.css",
    "css/extended/sidetoc.css",
    "css/extended/thumbnail.css"
  ]

[menu]
# [[menu.main]]
#   identifier = "project"
#   name = "Project"
#   url = "/projects/"
#   weight = 10
[[menu.main]]
  identifier = "coding"
  name = "Coding"
  url = "/coding/"
  weight = 20
[[menu.main]]
  identifier = "travel"
  name = "Travel"
  url = "/travel/"
  weight = 30
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 40
[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 50

